from __future__ import annotations

import re
from html import escape

CSS = """\
body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;max-width:800px;margin:0 auto;padding:40px 24px;color:#1a1a2e;background:#f4f2ee;line-height:1.7}
h1{font-size:1.75rem;font-weight:750;letter-spacing:-0.025em;margin:1.5em 0 0.5em}
h2{font-size:1.25rem;font-weight:700;letter-spacing:-0.02em;margin:1.5em 0 0.5em;border-bottom:1px solid #e5e5e0;padding-bottom:0.3em}
h3{font-size:1.1rem;font-weight:650;margin:1.2em 0 0.4em}
p{margin:0.6em 0}
ul,ol{padding-left:1.6em;margin:0.6em 0}
li{margin:0.3em 0}
code{border-radius:5px;background:#f1f5f9;padding:2px 6px;font-size:0.88em;color:#be185d;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
pre{border-radius:10px;background:#0f172a;color:#e2e8f0;padding:16px;overflow:auto;max-height:480px;line-height:1.7;font-size:13.5px}
pre code{background:none;padding:0;color:inherit;font-size:0.88em}
blockquote{border-left:3px solid #4f46e5;margin:0.8em 0;padding:0.4em 1em;color:#6b7280;background:#eef2ff;border-radius:0 6px 6px 0}
table{border-collapse:collapse;width:100%;margin:0.8em 0;font-size:14px}
th,td{border:1px solid #e5e5e0;padding:10px 14px;text-align:left}
th{background:#f8fafc;font-weight:650}
hr{border:none;border-top:1px solid #e5e5e0;margin:1.5em 0}
.header{margin-bottom:2em;padding-bottom:1em;border-bottom:2px solid #4f46e5}
.header h1{margin-top:0;color:#4f46e5}
.footer{margin-top:3em;padding-top:1em;border-top:1px solid #e5e5e0;color:#6b7280;font-size:0.85em;text-align:center}
"""


def build_report_html(title: str, markdown: str) -> str:
    html_body = _markdown_to_html(markdown)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<style>{CSS}</style>
</head>
<body>
<div class="header"><h1>{escape(title)}</h1></div>
{html_body}
<div class="footer">Generated by Paper2Repo</div>
</body>
</html>"""


def _markdown_to_html(md: str) -> str:
    lines: list[str] = []
    in_code = False
    code_lines: list[str] = []
    in_table = False
    table_rows: list[list[str]] = []

    def flush_code() -> None:
        nonlocal code_lines
        if code_lines:
            lines.append(f"<pre><code>{escape(chr(10).join(code_lines))}</code></pre>")
            code_lines = []

    def flush_table() -> None:
        nonlocal table_rows, in_table
        if not table_rows:
            return
        lines.append("<table>")
        for i, row in enumerate(table_rows):
            tag = "th" if i == 0 else "td"
            cells = "".join(f"<{tag}>{_inline(c)}</{tag}>" for c in row)
            lines.append(f"<tr>{cells}</tr>")
        lines.append("</table>")
        table_rows = []
        in_table = False

    for raw_line in md.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        if stripped.startswith("```"):
            if in_code:
                flush_code()
                in_code = False
            else:
                if in_table:
                    flush_table()
                in_code = True
                code_lines = []
            continue

        if in_code:
            code_lines.append(line)
            continue

        if not stripped:
            if in_table:
                flush_table()
            lines.append("")
            continue

        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= set("- :") for c in cells):
                continue
            table_rows.append(cells)
            in_table = True
            continue

        if in_table:
            flush_table()

        if stripped == "---":
            lines.append("<hr>")
            continue

        heading_match = re.match(r"^(#{1,4})\s+(.+)$", stripped)
        if heading_match:
            level = len(heading_match.group(1))
            lines.append(f"<h{level}>{_inline(heading_match.group(2))}</h{level}>")
            continue

        if stripped.startswith(">"):
            lines.append(f"<blockquote><p>{_inline(stripped.lstrip('> ').strip())}</p></blockquote>")
            continue

        bullet_match = re.match(r"^[-*]\s+(?:\[[ xX]\]\s+)?(.+)$", stripped)
        if bullet_match:
            lines.append(f"<li>{_inline(bullet_match.group(1))}</li>")
            continue

        ordered_match = re.match(r"^(\d+)\.\s+(.+)$", stripped)
        if ordered_match:
            lines.append(f"<li>{_inline(ordered_match.group(2))}</li>")
            continue

        lines.append(f"<p>{_inline(stripped)}</p>")

    flush_code()
    flush_table()
    return "\n".join(lines)


def _inline(text: str) -> str:
    s = escape(text)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"\*(.+?)\*", r"<em>\1</em>", s)
    s = re.sub(r"`(.+?)`", r"<code>\1</code>", s)
    s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)
    return s
