from app.repositories.analysis_jobs import (
    claim_analysis_job,
    complete_analysis_job,
    create_analysis_job,
    fail_analysis_job,
    get_analysis_job,
    is_analysis_cancel_requested,
    list_recoverable_analysis_jobs,
    request_analysis_cancel,
)
from app.repositories.citations import create_citations, get_citations_for_run
from app.repositories.connection import _json, get_connection, utc_now
from app.repositories.knowledge import (
    delete_embeddings,
    get_all_embeddings,
    get_paper_chunks,
    replace_chunks,
    save_embeddings,
)
from app.repositories.migrations import init_db
from app.repositories.papers import create_paper, get_paper, list_papers, update_paper_title
from app.repositories.qa import get_qa_history, save_qa_message
from app.repositories.reports import get_analysis_result, get_report, save_analysis_result, save_report
from app.repositories.runs import (
    STALE_RUN_ERROR_MESSAGE,
    create_batch_id,
    create_run,
    delete_run,
    get_run,
    get_runs_by_batch,
    list_runs,
    recover_stale_runs,
    update_run_status,
)
from app.repositories.settings import (
    DEFAULT_MODEL_SETTING_KEY,
    REPORT_LANGUAGE_SETTING_KEY,
    SUPPORTED_LANGUAGES,
    SUPPORTED_THEMES,
    THEME_SETTING_KEY,
    UI_LANGUAGE_SETTING_KEY,
    get_app_setting,
    get_default_model,
    get_report_language,
    get_theme,
    get_ui_language,
    set_app_setting,
    set_default_model,
    set_report_language,
    set_theme,
    set_ui_language,
)

__all__ = [
    "DEFAULT_MODEL_SETTING_KEY",
    "REPORT_LANGUAGE_SETTING_KEY",
    "STALE_RUN_ERROR_MESSAGE",
    "SUPPORTED_LANGUAGES",
    "SUPPORTED_THEMES",
    "THEME_SETTING_KEY",
    "UI_LANGUAGE_SETTING_KEY",
    "_json",
    "claim_analysis_job",
    "complete_analysis_job",
    "create_analysis_job",
    "create_batch_id",
    "create_citations",
    "create_paper",
    "create_run",
    "delete_embeddings",
    "delete_run",
    "fail_analysis_job",
    "get_all_embeddings",
    "get_analysis_job",
    "get_analysis_result",
    "get_app_setting",
    "get_citations_for_run",
    "get_connection",
    "get_default_model",
    "get_paper",
    "get_paper_chunks",
    "get_qa_history",
    "get_report",
    "get_report_language",
    "get_run",
    "get_runs_by_batch",
    "get_theme",
    "get_ui_language",
    "init_db",
    "is_analysis_cancel_requested",
    "list_papers",
    "list_recoverable_analysis_jobs",
    "list_runs",
    "recover_stale_runs",
    "replace_chunks",
    "request_analysis_cancel",
    "save_analysis_result",
    "save_embeddings",
    "save_qa_message",
    "save_report",
    "set_app_setting",
    "set_default_model",
    "set_report_language",
    "set_theme",
    "set_ui_language",
    "update_paper_title",
    "update_run_status",
    "utc_now",
]
